### ISSUE TITLE
ISPAppListController.m:169:5: error: implicit declaration of function 'Rlog' is invalid in C99 [-Werror,-Wimplicit-function-declaration]     Rlog(@"just testing a little be yes we are");

### ISSUE THREAD

**Issue by edwin170** [Muirey03/RemoteLog#2]
hi, it's my first time using this and could you please tell me what I should do with  implicit declaration of function 'Rlog' is invalid in C99. I imported it correctly

**Comment by Muirey03** [comment]
Capital 'L': RLog

**Comment by edwin170** [comment]
> Capital 'L': RLog

lmao sorry broooo

**Comment by edwin170** [comment]
and thank you
